import { ColorId, LiquidColorDef } from './types';

export const LIQUID_COLORS: Record<ColorId, LiquidColorDef> = {
  teal: {
    id: 'teal',
    name: 'Teal Ocean',
    namePt: 'Azul Petróleo',
    primary: '#0e7490',
    gradientTop: '#22d3ee',
    gradientBottom: '#0e7490',
    highlight: '#a5f3fc',
    stream: '#06b6d4',
    glow: 'rgba(14, 116, 144, 0.45)',
  },
  purple: {
    id: 'purple',
    name: 'Royal Purple',
    namePt: 'Roxo Real',
    primary: '#7c3aed',
    gradientTop: '#a78bfa',
    gradientBottom: '#6d28d9',
    highlight: '#ddd6fe',
    stream: '#8b5cf6',
    glow: 'rgba(124, 58, 237, 0.45)',
  },
  blue: {
    id: 'blue',
    name: 'Sky Blue',
    namePt: 'Azul Claro',
    primary: '#0284c7',
    gradientTop: '#38bdf8',
    gradientBottom: '#0369a1',
    highlight: '#bae6fd',
    stream: '#0ea5e9',
    glow: 'rgba(2, 132, 199, 0.45)',
  },
  pink: {
    id: 'pink',
    name: 'Rose Pink',
    namePt: 'Rosa Choque',
    primary: '#ec4899',
    gradientTop: '#f472b6',
    gradientBottom: '#db2777',
    highlight: '#fbcfe8',
    stream: '#f43f5e',
    glow: 'rgba(236, 72, 153, 0.45)',
  },
  yellow: {
    id: 'yellow',
    name: 'Golden Yellow',
    namePt: 'Amarelo Ouro',
    primary: '#eab308',
    gradientTop: '#fde047',
    gradientBottom: '#ca8a04',
    highlight: '#fef08a',
    stream: '#facc15',
    glow: 'rgba(234, 179, 8, 0.45)',
  },
  green: {
    id: 'green',
    name: 'Emerald Green',
    namePt: 'Verde Esmeralda',
    primary: '#16a34a',
    gradientTop: '#4ade80',
    gradientBottom: '#15803d',
    highlight: '#bbf7d0',
    stream: '#22c55e',
    glow: 'rgba(22, 163, 74, 0.45)',
  },
  orange: {
    id: 'orange',
    name: 'Vibrant Orange',
    namePt: 'Laranja Vivo',
    primary: '#ea580c',
    gradientTop: '#fb923c',
    gradientBottom: '#c2410c',
    highlight: '#fed7aa',
    stream: '#f97316',
    glow: 'rgba(234, 88, 12, 0.45)',
  },
  red: {
    id: 'red',
    name: 'Ruby Red',
    namePt: 'Vermelho Rubi',
    primary: '#dc2626',
    gradientTop: '#f87171',
    gradientBottom: '#b91c1c',
    highlight: '#fecaca',
    stream: '#ef4444',
    glow: 'rgba(220, 38, 38, 0.45)',
  },
  violet: {
    id: 'violet',
    name: 'Deep Violet',
    namePt: 'Violeta Intenso',
    primary: '#9333ea',
    gradientTop: '#c084fc',
    gradientBottom: '#7e22ce',
    highlight: '#e9d5ff',
    stream: '#a855f7',
    glow: 'rgba(147, 51, 234, 0.45)',
  },
  lime: {
    id: 'lime',
    name: 'Electric Lime',
    namePt: 'Verde Limão',
    primary: '#65a30d',
    gradientTop: '#a3e635',
    gradientBottom: '#4d7c0f',
    highlight: '#d9f99d',
    stream: '#84cc16',
    glow: 'rgba(101, 163, 13, 0.45)',
  },
};
