import { LevelData } from './types';

export const LEVELS: LevelData[] = [
  // --- LEVELS 1 TO 5: EASY (INTRO & CONCEPTS) ---
  {
    id: 1,
    name: 'First Steps',
    difficulty: 'Easy',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 4,
    blocks: [
      { id: 'key', x: 1, y: 2, width: 2, height: 1, isKey: true },
      { id: 'b1', x: 3, y: 1, width: 1, height: 2 },
      { id: 'b2', x: 0, y: 0, width: 2, height: 1 },
      { id: 'b3', x: 4, y: 2, width: 1, height: 3 },
      { id: 'b4', x: 1, y: 4, width: 3, height: 1 },
    ],
  },
  {
    id: 2,
    name: 'Clear Path',
    difficulty: 'Easy',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 6,
    blocks: [
      { id: 'key', x: 0, y: 2, width: 2, height: 1, isKey: true },
      { id: 'b1', x: 2, y: 1, width: 1, height: 2 },
      { id: 'b2', x: 2, y: 3, width: 1, height: 2 },
      { id: 'b3', x: 3, y: 1, width: 2, height: 1 },
      { id: 'b4', x: 4, y: 2, width: 1, height: 2 },
      { id: 'b5', x: 0, y: 4, width: 2, height: 1 },
    ],
  },
  {
    id: 3,
    name: 'Double Opening',
    difficulty: 'Easy',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 8,
    blocks: [
      { id: 'key', x: 1, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 0, y: 1, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 0, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 2, width: 1, height: 3 },
      { id: 'h1', x: 0, y: 0, width: 3, height: 1 },
      { id: 'h2', x: 1, y: 4, width: 2, height: 1 },
      { id: 'h3', x: 2, y: 5, width: 3, height: 1 },
    ],
  },
  {
    id: 4,
    name: 'Wooden Guardian',
    difficulty: 'Easy',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 9,
    blocks: [
      { id: 'key', x: 0, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 2, y: 0, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 1, width: 1, height: 3 },
      { id: 'v3', x: 5, y: 0, width: 1, height: 3 },
      { id: 'h1', x: 3, y: 0, width: 2, height: 1 },
      { id: 'h2', x: 0, y: 3, width: 2, height: 1 },
      { id: 'h3', x: 0, y: 4, width: 3, height: 1 },
      { id: 'h4', x: 3, y: 4, width: 3, height: 1 },
    ],
  },
  {
    id: 5,
    name: 'Smooth Slide',
    difficulty: 'Easy',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 10,
    blocks: [
      { id: 'key', x: 1, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', x: 3, y: 1, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v4', x: 5, y: 1, width: 1, height: 3 },
      { id: 'h1', x: 1, y: 0, width: 3, height: 1 },
      { id: 'h2', x: 0, y: 4, width: 2, height: 1 },
      { id: 'h3', x: 2, y: 5, width: 3, height: 1 },
    ],
  },

  // --- LEVELS 6 TO 12: MEDIUM (STRATEGY & EXPANDED BOARDS) ---
  {
    id: 6,
    name: 'Narrow Crossing',
    difficulty: 'Medium',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 12,
    blocks: [
      { id: 'key', x: 0, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 2, y: 1, width: 1, height: 2 },
      { id: 'v2', x: 3, y: 2, width: 1, height: 2 },
      { id: 'v3', x: 4, y: 0, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 2, width: 1, height: 3 },
      { id: 'h1', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h2', x: 1, y: 4, width: 2, height: 1 },
      { id: 'h3', x: 0, y: 5, width: 3, height: 1 },
      { id: 'h4', x: 3, y: 5, width: 2, height: 1 },
    ],
  },
  {
    id: 7,
    name: 'Oak Gears',
    difficulty: 'Medium',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 14,
    blocks: [
      { id: 'key', x: 1, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 0, y: 0, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 0, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 1, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 2, width: 1, height: 2 },
      { id: 'h1', x: 1, y: 0, width: 2, height: 1 },
      { id: 'h2', x: 1, y: 3, width: 2, height: 1 },
      { id: 'h3', x: 0, y: 4, width: 2, height: 1 },
      { id: 'h4', x: 2, y: 5, width: 3, height: 1 },
    ],
  },
  {
    id: 8,
    name: 'Golden Key',
    difficulty: 'Medium',
    cols: 8,
    rows: 6,
    exitRow: 2,
    exitCol: 7,
    exitSide: 'right',
    targetMoves: 13,
    blocks: [
      { id: 'key', x: 2, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 1, y: 1, width: 1, height: 3 },
      { id: 'v2', x: 4, y: 0, width: 1, height: 3 },
      { id: 'v3', x: 5, y: 2, width: 1, height: 3 },
      { id: 'v4', x: 6, y: 1, width: 1, height: 3 },
      { id: 'h1', x: 1, y: 0, width: 3, height: 1 },
      { id: 'h2', x: 2, y: 3, width: 2, height: 1 },
      { id: 'h3', x: 0, y: 4, width: 3, height: 1 },
      { id: 'h4', x: 3, y: 5, width: 4, height: 1 },
    ],
  },
  {
    id: 9,
    name: 'Imperial Maze',
    difficulty: 'Medium',
    cols: 10,
    rows: 6,
    exitRow: 2,
    exitCol: 9,
    exitSide: 'right',
    targetMoves: 15,
    blocks: [
      { id: 'key', x: 4, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 1, y: 0, width: 1, height: 2 },
      { id: 'v2', x: 1, y: 3, width: 1, height: 2 },
      { id: 'v3', x: 2, y: 2, width: 1, height: 2 },
      { id: 'h1', x: 3, y: 0, width: 3, height: 1 },
      { id: 'b_sq', x: 5, y: 1, width: 1, height: 1 },
      { id: 'h2', x: 4, y: 3, width: 3, height: 1 },
      { id: 'h3', x: 3, y: 4, width: 3, height: 1 },
      { id: 'v4', x: 7, y: 1, width: 1, height: 2 },
      { id: 'v5', x: 7, y: 3, width: 1, height: 2 },
    ],
  },
  {
    id: 10,
    name: 'Mahogany Wall',
    difficulty: 'Medium',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 16,
    blocks: [
      { id: 'key', x: 0, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 2, y: 0, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 1, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 2, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 0, width: 1, height: 2 },
      { id: 'h1', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h2', x: 0, y: 3, width: 2, height: 1 },
      { id: 'h3', x: 0, y: 5, width: 3, height: 1 },
      { id: 'h4', x: 3, y: 4, width: 2, height: 1 },
    ],
  },
  {
    id: 11,
    name: 'Hidden Corridor',
    difficulty: 'Medium',
    cols: 8,
    rows: 6,
    exitRow: 2,
    exitCol: 7,
    exitSide: 'right',
    targetMoves: 17,
    blocks: [
      { id: 'key', x: 1, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 0, y: 1, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 0, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 1, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 2, width: 1, height: 3 },
      { id: 'v5', x: 6, y: 0, width: 1, height: 2 },
      { id: 'h1', x: 0, y: 0, width: 3, height: 1 },
      { id: 'h2', x: 1, y: 4, width: 3, height: 1 },
      { id: 'h3', x: 4, y: 4, width: 3, height: 1 },
      { id: 'h4', x: 2, y: 5, width: 4, height: 1 },
    ],
  },
  {
    id: 12,
    name: 'Drawbridge',
    difficulty: 'Medium',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 18,
    blocks: [
      { id: 'key', x: 1, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 0, y: 0, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 0, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 1, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 1, width: 1, height: 3 },
      { id: 'h1', x: 1, y: 0, width: 2, height: 1 },
      { id: 'h2', x: 0, y: 3, width: 3, height: 1 },
      { id: 'h3', x: 0, y: 4, width: 2, height: 1 },
      { id: 'h4', x: 2, y: 5, width: 3, height: 1 },
    ],
  },

  // --- LEVELS 13 TO 18: HARD (INTRICATE & DEEP) ---
  {
    id: 13,
    name: 'The Royal Vault',
    difficulty: 'Hard',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 21,
    blocks: [
      { id: 'key', x: 1, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 0, y: 1, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 1, width: 1, height: 2 },
      { id: 'v3', x: 4, y: 0, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 2, width: 1, height: 3 },
      { id: 'h1', x: 0, y: 0, width: 3, height: 1 },
      { id: 'h2', x: 1, y: 3, width: 2, height: 1 },
      { id: 'h3', x: 1, y: 4, width: 3, height: 1 },
      { id: 'h4', x: 0, y: 5, width: 3, height: 1 },
      { id: 'h5', x: 3, y: 5, width: 2, height: 1 },
    ],
  },
  {
    id: 14,
    name: 'Ebony Cylinders',
    difficulty: 'Hard',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 23,
    blocks: [
      { id: 'key', x: 0, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 2, y: 1, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 0, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 2, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 1, width: 1, height: 3 },
      { id: 'h1', x: 0, y: 0, width: 3, height: 1 },
      { id: 'h2', x: 0, y: 1, width: 2, height: 1 },
      { id: 'h3', x: 0, y: 4, width: 2, height: 1 },
      { id: 'h4', x: 0, y: 5, width: 3, height: 1 },
      { id: 'h5', x: 3, y: 5, width: 3, height: 1 },
    ],
  },
  {
    id: 15,
    name: 'Grand Chamber',
    difficulty: 'Hard',
    cols: 10,
    rows: 6,
    exitRow: 2,
    exitCol: 9,
    exitSide: 'right',
    targetMoves: 24,
    blocks: [
      { id: 'key', x: 3, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 1, y: 0, width: 1, height: 3 },
      { id: 'v2', x: 2, y: 2, width: 1, height: 3 },
      { id: 'v3', x: 5, y: 1, width: 1, height: 3 },
      { id: 'v4', x: 6, y: 0, width: 1, height: 3 },
      { id: 'v5', x: 7, y: 2, width: 1, height: 3 },
      { id: 'v6', x: 8, y: 1, width: 1, height: 3 },
      { id: 'h1', x: 2, y: 0, width: 3, height: 1 },
      { id: 'h2', x: 3, y: 4, width: 3, height: 1 },
      { id: 'h3', x: 6, y: 5, width: 3, height: 1 },
      { id: 'h4', x: 0, y: 5, width: 3, height: 1 },
    ],
  },
  {
    id: 16,
    name: 'Secret Passage',
    difficulty: 'Hard',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 25,
    blocks: [
      { id: 'key', x: 1, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 0, y: 0, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 0, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 1, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 0, width: 1, height: 2 },
      { id: 'h1', x: 1, y: 0, width: 2, height: 1 },
      { id: 'h2', x: 1, y: 1, width: 2, height: 1 },
      { id: 'h3', x: 0, y: 3, width: 2, height: 1 },
      { id: 'h4', x: 0, y: 4, width: 3, height: 1 },
      { id: 'h5', x: 2, y: 5, width: 3, height: 1 },
    ],
  },
  {
    id: 17,
    name: 'Cedar Prison',
    difficulty: 'Hard',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 27,
    blocks: [
      { id: 'key', x: 0, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 2, y: 0, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 1, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v4', x: 4, y: 3, width: 1, height: 3 },
      { id: 'v5', x: 5, y: 1, width: 1, height: 3 },
      { id: 'h1', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h2', x: 0, y: 1, width: 2, height: 1 },
      { id: 'h3', x: 0, y: 4, width: 2, height: 1 },
      { id: 'h4', x: 1, y: 5, width: 3, height: 1 },
    ],
  },
  {
    id: 18,
    name: 'The Gordian Knot',
    difficulty: 'Hard',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 28,
    blocks: [
      { id: 'key', x: 1, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 0, y: 1, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 0, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 2, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 1, width: 1, height: 3 },
      { id: 'h1', x: 0, y: 0, width: 3, height: 1 },
      { id: 'h2', x: 1, y: 3, width: 2, height: 1 },
      { id: 'h3', x: 0, y: 4, width: 2, height: 1 },
      { id: 'h4', x: 2, y: 4, width: 2, height: 1 },
      { id: 'h5', x: 1, y: 5, width: 3, height: 1 },
    ],
  },

  // --- LEVELS 19 TO 25: MASTER (ADVANCED PUZZLES) ---
  {
    id: 19,
    name: 'Forbidden Sanctuary',
    difficulty: 'Master',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 31,
    blocks: [
      { id: 'key', x: 0, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 2, y: 1, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 0, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 1, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 0, width: 1, height: 3 },
      { id: 'h1', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h2', x: 0, y: 1, width: 2, height: 1 },
      { id: 'h3', x: 0, y: 4, width: 2, height: 1 },
      { id: 'h4', x: 2, y: 4, width: 2, height: 1 },
      { id: 'h5', x: 1, y: 5, width: 3, height: 1 },
      { id: 'h6', x: 4, y: 5, width: 2, height: 1 },
    ],
  },
  {
    id: 20,
    name: "Archivist's Enigma",
    difficulty: 'Master',
    cols: 8,
    rows: 6,
    exitRow: 2,
    exitCol: 7,
    exitSide: 'right',
    targetMoves: 33,
    blocks: [
      { id: 'key', x: 1, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 0, y: 0, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 1, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 0, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 2, width: 1, height: 3 },
      { id: 'v5', x: 6, y: 1, width: 1, height: 3 },
      { id: 'v6', x: 7, y: 0, width: 1, height: 2 },
      { id: 'h1', x: 1, y: 0, width: 3, height: 1 },
      { id: 'h2', x: 0, y: 3, width: 3, height: 1 },
      { id: 'h3', x: 1, y: 4, width: 3, height: 1 },
      { id: 'h4', x: 4, y: 5, width: 3, height: 1 },
    ],
  },
  {
    id: 21,
    name: 'Primordial Mechanism',
    difficulty: 'Master',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 36,
    blocks: [
      { id: 'key', x: 0, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 2, y: 0, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 1, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 2, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 0, width: 1, height: 3 },
      { id: 'h1', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h2', x: 0, y: 1, width: 2, height: 1 },
      { id: 'h3', x: 0, y: 3, width: 2, height: 1 },
      { id: 'h4', x: 0, y: 4, width: 3, height: 1 },
      { id: 'h5', x: 2, y: 5, width: 3, height: 1 },
    ],
  },
  {
    id: 22,
    name: 'The Great Lockup',
    difficulty: 'Master',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 38,
    blocks: [
      { id: 'key', x: 1, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 0, y: 1, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 0, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 1, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 1, width: 1, height: 3 },
      { id: 'h1', x: 0, y: 0, width: 3, height: 1 },
      { id: 'h2', x: 1, y: 1, width: 2, height: 1 },
      { id: 'h3', x: 1, y: 3, width: 2, height: 1 },
      { id: 'h4', x: 0, y: 4, width: 3, height: 1 },
      { id: 'h5', x: 1, y: 5, width: 3, height: 1 },
    ],
  },
  {
    id: 23,
    name: 'Key of Kings',
    difficulty: 'Master',
    cols: 10,
    rows: 6,
    exitRow: 2,
    exitCol: 9,
    exitSide: 'right',
    targetMoves: 40,
    blocks: [
      { id: 'key', x: 2, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 0, y: 0, width: 1, height: 3 },
      { id: 'v2', x: 1, y: 2, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 0, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 2, width: 1, height: 3 },
      { id: 'v5', x: 6, y: 1, width: 1, height: 3 },
      { id: 'v6', x: 7, y: 2, width: 1, height: 3 },
      { id: 'v7', x: 8, y: 0, width: 1, height: 3 },
      { id: 'h1', x: 1, y: 0, width: 3, height: 1 },
      { id: 'h2', x: 2, y: 4, width: 3, height: 1 },
      { id: 'h3', x: 5, y: 5, width: 3, height: 1 },
      { id: 'h4', x: 0, y: 5, width: 2, height: 1 },
    ],
  },
  {
    id: 24,
    name: 'Endless Labyrinth',
    difficulty: 'Master',
    cols: 8,
    rows: 6,
    exitRow: 2,
    exitCol: 7,
    exitSide: 'right',
    targetMoves: 42,
    blocks: [
      { id: 'key', x: 1, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 0, y: 1, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 0, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 1, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 2, width: 1, height: 3 },
      { id: 'v5', x: 6, y: 0, width: 1, height: 3 },
      { id: 'h1', x: 0, y: 0, width: 3, height: 1 },
      { id: 'h2', x: 1, y: 3, width: 2, height: 1 },
      { id: 'h3', x: 1, y: 4, width: 3, height: 1 },
      { id: 'h4', x: 4, y: 4, width: 2, height: 1 },
      { id: 'h5', x: 2, y: 5, width: 4, height: 1 },
    ],
  },
  {
    id: 25,
    name: 'Block Master',
    difficulty: 'Master',
    cols: 6,
    rows: 6,
    exitRow: 2,
    exitCol: 5,
    exitSide: 'right',
    targetMoves: 45,
    blocks: [
      { id: 'key', x: 0, y: 2, width: 2, height: 1, isKey: true },
      { id: 'v1', x: 2, y: 1, width: 1, height: 3 },
      { id: 'v2', x: 3, y: 0, width: 1, height: 3 },
      { id: 'v3', x: 4, y: 2, width: 1, height: 3 },
      { id: 'v4', x: 5, y: 0, width: 1, height: 3 },
      { id: 'h1', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h2', x: 0, y: 1, width: 2, height: 1 },
      { id: 'h3', x: 0, y: 3, width: 2, height: 1 },
      { id: 'h4', x: 0, y: 4, width: 2, height: 1 },
      { id: 'h5', x: 2, y: 4, width: 2, height: 1 },
      { id: 'h6', x: 1, y: 5, width: 3, height: 1 },
      { id: 'h7', x: 4, y: 5, width: 2, height: 1 },
    ],
  },
];
