/**
 * 30 Handcrafted Progression Levels for City Parking Jam
 * Vehicles:
 * - sedan: 1x2 grid size, fast acceleration
 * - suv: 1x2 grid size, standard
 * - van: 1x3 grid size, large turn radius & longer length
 */

export const SKINS_DATA = [
  {
    id: 'default',
    name: 'Urban Classic',
    description: 'Standard city asphalt collection',
    icon: '🚗',
    starsRequired: 0,
    themeColor: '#3b82f6',
  },
  {
    id: 'taxi',
    name: 'Yellow Cab Taxi',
    description: 'Bright NYC checkered cab styling',
    icon: '🚕',
    starsRequired: 6,
    themeColor: '#eab308',
  },
  {
    id: 'police',
    name: 'Highway Patrol',
    description: 'Pursuit interceptor with flashing blue/red lights',
    icon: '🚓',
    starsRequired: 15,
    themeColor: '#3b82f6',
  },
  {
    id: 'fire',
    name: 'Fire Chief Engine',
    description: 'High-visibility emergency red & gold',
    icon: '🚒',
    starsRequired: 24,
    themeColor: '#ef4444',
  },
  {
    id: 'cyber',
    name: 'Cyber Neon Pulse',
    description: 'Midnight carbon fiber with neon cyan lights',
    icon: '🏎️',
    starsRequired: 35,
    themeColor: '#06b6d4',
  },
  {
    id: 'gold',
    name: '24K Golden Luxury',
    description: 'Pure polished gold finish with gold sparkle trails',
    icon: '👑',
    starsRequired: 50,
    themeColor: '#f59e0b',
  },
];

export const TRAILS_DATA = [
  {
    id: 'smoke',
    name: 'Tire Burnout Smoke',
    description: 'White tire friction clouds',
    icon: '💨',
    starsRequired: 0,
  },
  {
    id: 'nitro',
    name: 'Nitrous Blue Flame',
    description: 'High-octane blue plasma bursts',
    icon: '🔥',
    starsRequired: 10,
  },
  {
    id: 'spark',
    name: 'Electric Sparks',
    description: 'Golden grinding sparks',
    icon: '⚡',
    starsRequired: 20,
  },
  {
    id: 'rainbow',
    name: 'Rainbow Prism',
    description: 'Multicolor rainbow speed trail',
    icon: '🌈',
    starsRequired: 40,
  },
];

export const ALL_LEVELS = [
  // 1. Easy Tutorials (1 - 5)
  {
    levelNumber: 1,
    difficulty: 'Easy',
    gridWidth: 4,
    gridHeight: 4,
    parMoves: 2,
    cars: [
      { id: 'c1', x: 0, y: 1, length: 2, direction: 'RIGHT', color: '#3b82f6', type: 'sedan' },
      { id: 'c2', x: 2, y: 2, length: 2, direction: 'DOWN', color: '#ef4444', type: 'suv' },
    ],
    obstacles: [],
  },
  {
    levelNumber: 2,
    difficulty: 'Easy',
    gridWidth: 4,
    gridHeight: 4,
    parMoves: 3,
    cars: [
      { id: 'c1', x: 1, y: 0, length: 2, direction: 'DOWN', color: '#10b981', type: 'sedan' },
      { id: 'c2', x: 2, y: 2, length: 2, direction: 'RIGHT', color: '#f59e0b', type: 'sedan' },
      { id: 'c3', x: 0, y: 3, length: 2, direction: 'LEFT', color: '#8b5cf6', type: 'sedan' },
    ],
    obstacles: [],
  },
  {
    levelNumber: 3,
    difficulty: 'Easy',
    gridWidth: 5,
    gridHeight: 5,
    parMoves: 4,
    cars: [
      { id: 'c1', x: 1, y: 0, length: 2, direction: 'UP', color: '#3b82f6', type: 'sedan' },
      { id: 'c2', x: 2, y: 1, length: 3, direction: 'RIGHT', color: '#6366f1', type: 'van' },
      { id: 'c3', x: 2, y: 3, length: 2, direction: 'DOWN', color: '#ec4899', type: 'suv' },
      { id: 'c4', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#14b8a6', type: 'sedan' },
    ],
    obstacles: [],
  },
  {
    levelNumber: 4,
    difficulty: 'Easy',
    gridWidth: 5,
    gridHeight: 5,
    parMoves: 4,
    cars: [
      { id: 'c1', x: 1, y: 0, length: 3, direction: 'DOWN', color: '#f97316', type: 'van' },
      { id: 'c2', x: 2, y: 1, length: 2, direction: 'RIGHT', color: '#3b82f6', type: 'sedan' },
      { id: 'c3', x: 3, y: 3, length: 2, direction: 'DOWN', color: '#10b981', type: 'suv' },
      { id: 'c4', x: 0, y: 4, length: 2, direction: 'LEFT', color: '#ef4444', type: 'sedan' },
    ],
    obstacles: [{ id: 'o1', x: 4, y: 0, width: 1, height: 1, type: 'cone' }],
  },
  {
    levelNumber: 5,
    difficulty: 'Easy',
    gridWidth: 5,
    gridHeight: 5,
    parMoves: 5,
    cars: [
      { id: 'c1', x: 0, y: 0, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c2', x: 2, y: 0, length: 2, direction: 'DOWN', color: '#ef4444', type: 'sedan' },
      { id: 'c3', x: 3, y: 2, length: 2, direction: 'RIGHT', color: '#10b981', type: 'sedan' },
      { id: 'c4', x: 1, y: 2, length: 3, direction: 'DOWN', color: '#06b6d4', type: 'van' },
      { id: 'c5', x: 2, y: 4, length: 2, direction: 'RIGHT', color: '#f59e0b', type: 'suv' },
    ],
    obstacles: [{ id: 'o1', x: 4, y: 4, width: 1, height: 1, type: 'hydrant' }],
  },

  // 2. Medium Levels (6 - 15)
  {
    levelNumber: 6,
    difficulty: 'Medium',
    gridWidth: 5,
    gridHeight: 5,
    parMoves: 5,
    cars: [
      { id: 'c1', x: 1, y: 0, length: 2, direction: 'UP', color: '#3b82f6', type: 'sedan' },
      { id: 'c2', x: 2, y: 1, length: 3, direction: 'RIGHT', color: '#f43f5e', type: 'van' },
      { id: 'c3', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#10b981', type: 'sedan' },
      { id: 'c4', x: 3, y: 2, length: 2, direction: 'DOWN', color: '#eab308', type: 'suv' },
      { id: 'c5', x: 1, y: 4, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'sedan' },
    ],
    obstacles: [{ id: 'o1', x: 0, y: 4, width: 1, height: 1, type: 'barrier' }],
  },
  {
    levelNumber: 7,
    difficulty: 'Medium',
    gridWidth: 6,
    gridHeight: 6,
    parMoves: 6,
    cars: [
      { id: 'c1', x: 0, y: 1, length: 2, direction: 'RIGHT', color: '#0ea5e9', type: 'sedan' },
      { id: 'c2', x: 2, y: 1, length: 2, direction: 'DOWN', color: '#f59e0b', type: 'suv' },
      { id: 'c3', x: 4, y: 0, length: 3, direction: 'DOWN', color: '#6366f1', type: 'van' },
      { id: 'c4', x: 1, y: 3, length: 3, direction: 'RIGHT', color: '#10b981', type: 'van' },
      { id: 'c5', x: 0, y: 4, length: 2, direction: 'LEFT', color: '#ef4444', type: 'sedan' },
      { id: 'c6', x: 3, y: 4, length: 2, direction: 'DOWN', color: '#ec4899', type: 'sedan' },
    ],
    obstacles: [{ id: 'o1', x: 5, y: 5, width: 1, height: 1, type: 'planter' }],
  },
  {
    levelNumber: 8,
    difficulty: 'Medium',
    gridWidth: 6,
    gridHeight: 6,
    parMoves: 6,
    cars: [
      { id: 'c1', x: 2, y: 0, length: 2, direction: 'UP', color: '#3b82f6', type: 'sedan' },
      { id: 'c2', x: 0, y: 2, length: 3, direction: 'RIGHT', color: '#14b8a6', type: 'van' },
      { id: 'c3', x: 3, y: 1, length: 2, direction: 'DOWN', color: '#f97316', type: 'suv' },
      { id: 'c4', x: 4, y: 2, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c5', x: 1, y: 4, length: 2, direction: 'DOWN', color: '#e11d48', type: 'sedan' },
      { id: 'c6', x: 3, y: 5, length: 3, direction: 'RIGHT', color: '#06b6d4', type: 'van' },
    ],
    obstacles: [
      { id: 'o1', x: 0, y: 0, width: 1, height: 1, type: 'cone' },
      { id: 'o2', x: 5, y: 0, width: 1, height: 1, type: 'cone' },
    ],
  },
  {
    levelNumber: 9,
    difficulty: 'Medium',
    gridWidth: 6,
    gridHeight: 6,
    parMoves: 7,
    cars: [
      { id: 'c1', x: 1, y: 1, length: 2, direction: 'RIGHT', color: '#ef4444', type: 'sedan' },
      { id: 'c2', x: 3, y: 0, length: 2, direction: 'DOWN', color: '#3b82f6', type: 'suv' },
      { id: 'c3', x: 4, y: 2, length: 2, direction: 'RIGHT', color: '#10b981', type: 'sedan' },
      { id: 'c4', x: 0, y: 3, length: 3, direction: 'RIGHT', color: '#f59e0b', type: 'van' },
      { id: 'c5', x: 3, y: 3, length: 2, direction: 'DOWN', color: '#8b5cf6', type: 'sedan' },
      { id: 'c6', x: 1, y: 4, length: 2, direction: 'LEFT', color: '#06b6d4', type: 'sedan' },
      { id: 'c7', x: 4, y: 4, length: 2, direction: 'DOWN', color: '#f43f5e', type: 'suv' },
    ],
    obstacles: [{ id: 'o1', x: 2, y: 5, width: 1, height: 1, type: 'barrier' }],
  },
  {
    levelNumber: 10,
    difficulty: 'Medium',
    gridWidth: 6,
    gridHeight: 6,
    parMoves: 7,
    cars: [
      { id: 'c1', x: 0, y: 0, length: 3, direction: 'RIGHT', color: '#f97316', type: 'van' },
      { id: 'c2', x: 3, y: 0, length: 2, direction: 'DOWN', color: '#10b981', type: 'suv' },
      { id: 'c3', x: 1, y: 1, length: 2, direction: 'DOWN', color: '#3b82f6', type: 'sedan' },
      { id: 'c4', x: 4, y: 2, length: 2, direction: 'RIGHT', color: '#eab308', type: 'sedan' },
      { id: 'c5', x: 0, y: 4, length: 2, direction: 'LEFT', color: '#ec4899', type: 'sedan' },
      { id: 'c6', x: 2, y: 3, length: 3, direction: 'DOWN', color: '#6366f1', type: 'van' },
      { id: 'c7', x: 3, y: 5, length: 2, direction: 'RIGHT', color: '#14b8a6', type: 'suv' },
    ],
    obstacles: [
      { id: 'o1', x: 5, y: 1, width: 1, height: 1, type: 'hydrant' },
      { id: 'o2', x: 0, y: 5, width: 1, height: 1, type: 'planter' },
    ],
  },
  {
    levelNumber: 11,
    difficulty: 'Medium',
    gridWidth: 6,
    gridHeight: 6,
    parMoves: 7,
    cars: [
      { id: 'c1', x: 0, y: 1, length: 2, direction: 'RIGHT', color: '#ef4444', type: 'sedan' },
      { id: 'c2', x: 2, y: 0, length: 3, direction: 'DOWN', color: '#f59e0b', type: 'van' },
      { id: 'c3', x: 3, y: 1, length: 2, direction: 'RIGHT', color: '#10b981', type: 'sedan' },
      { id: 'c4', x: 5, y: 2, length: 2, direction: 'DOWN', color: '#3b82f6', type: 'suv' },
      { id: 'c5', x: 0, y: 3, length: 2, direction: 'LEFT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c6', x: 3, y: 3, length: 3, direction: 'DOWN', color: '#ec4899', type: 'van' },
      { id: 'c7', x: 1, y: 5, length: 2, direction: 'RIGHT', color: '#06b6d4', type: 'sedan' },
    ],
    obstacles: [{ id: 'o1', x: 0, y: 0, width: 1, height: 1, type: 'cone' }],
  },
  {
    levelNumber: 12,
    difficulty: 'Medium',
    gridWidth: 6,
    gridHeight: 6,
    parMoves: 8,
    cars: [
      { id: 'c1', x: 1, y: 0, length: 2, direction: 'UP', color: '#3b82f6', type: 'sedan' },
      { id: 'c2', x: 3, y: 0, length: 2, direction: 'DOWN', color: '#ef4444', type: 'suv' },
      { id: 'c3', x: 0, y: 2, length: 3, direction: 'RIGHT', color: '#6366f1', type: 'van' },
      { id: 'c4', x: 4, y: 1, length: 2, direction: 'RIGHT', color: '#10b981', type: 'sedan' },
      { id: 'c5', x: 2, y: 3, length: 2, direction: 'DOWN', color: '#f59e0b', type: 'sedan' },
      { id: 'c6', x: 4, y: 3, length: 3, direction: 'DOWN', color: '#f43f5e', type: 'van' },
      { id: 'c7', x: 0, y: 4, length: 2, direction: 'LEFT', color: '#14b8a6', type: 'sedan' },
      { id: 'c8', x: 1, y: 5, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'suv' },
    ],
    obstacles: [{ id: 'o1', x: 5, y: 0, width: 1, height: 1, type: 'barrier' }],
  },
  {
    levelNumber: 13,
    difficulty: 'Medium',
    gridWidth: 6,
    gridHeight: 6,
    parMoves: 8,
    cars: [
      { id: 'c1', x: 0, y: 0, length: 2, direction: 'RIGHT', color: '#10b981', type: 'sedan' },
      { id: 'c2', x: 2, y: 0, length: 3, direction: 'DOWN', color: '#f97316', type: 'van' },
      { id: 'c3', x: 3, y: 0, length: 2, direction: 'RIGHT', color: '#3b82f6', type: 'suv' },
      { id: 'c4', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#ef4444', type: 'sedan' },
      { id: 'c5', x: 3, y: 2, length: 2, direction: 'DOWN', color: '#8b5cf6', type: 'sedan' },
      { id: 'c6', x: 4, y: 2, length: 2, direction: 'RIGHT', color: '#06b6d4', type: 'sedan' },
      { id: 'c7', x: 0, y: 4, length: 3, direction: 'RIGHT', color: '#ec4899', type: 'van' },
      { id: 'c8', x: 3, y: 4, length: 2, direction: 'DOWN', color: '#eab308', type: 'suv' },
    ],
    obstacles: [{ id: 'o1', x: 5, y: 5, width: 1, height: 1, type: 'cone' }],
  },
  {
    levelNumber: 14,
    difficulty: 'Medium',
    gridWidth: 7,
    gridHeight: 7,
    parMoves: 8,
    cars: [
      { id: 'c1', x: 1, y: 1, length: 2, direction: 'UP', color: '#3b82f6', type: 'sedan' },
      { id: 'c2', x: 2, y: 1, length: 3, direction: 'RIGHT', color: '#6366f1', type: 'van' },
      { id: 'c3', x: 5, y: 0, length: 2, direction: 'DOWN', color: '#ef4444', type: 'suv' },
      { id: 'c4', x: 0, y: 3, length: 2, direction: 'LEFT', color: '#10b981', type: 'sedan' },
      { id: 'c5', x: 3, y: 2, length: 3, direction: 'DOWN', color: '#f59e0b', type: 'van' },
      { id: 'c6', x: 4, y: 3, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c7', x: 1, y: 5, length: 3, direction: 'RIGHT', color: '#14b8a6', type: 'van' },
      { id: 'c8', x: 5, y: 4, length: 2, direction: 'DOWN', color: '#ec4899', type: 'suv' },
    ],
    obstacles: [
      { id: 'o1', x: 0, y: 0, width: 1, height: 1, type: 'planter' },
      { id: 'o2', x: 6, y: 6, width: 1, height: 1, type: 'hydrant' },
    ],
  },
  {
    levelNumber: 15,
    difficulty: 'Medium',
    gridWidth: 7,
    gridHeight: 7,
    parMoves: 9,
    cars: [
      { id: 'c1', x: 0, y: 0, length: 3, direction: 'RIGHT', color: '#f97316', type: 'van' },
      { id: 'c2', x: 3, y: 0, length: 2, direction: 'DOWN', color: '#3b82f6', type: 'sedan' },
      { id: 'c3', x: 4, y: 1, length: 2, direction: 'RIGHT', color: '#10b981', type: 'suv' },
      { id: 'c4', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#ef4444', type: 'sedan' },
      { id: 'c5', x: 2, y: 2, length: 3, direction: 'DOWN', color: '#6366f1', type: 'van' },
      { id: 'c6', x: 5, y: 2, length: 2, direction: 'DOWN', color: '#8b5cf6', type: 'sedan' },
      { id: 'c7', x: 0, y: 4, length: 2, direction: 'RIGHT', color: '#06b6d4', type: 'suv' },
      { id: 'c8', x: 3, y: 4, length: 2, direction: 'DOWN', color: '#ec4899', type: 'sedan' },
      { id: 'c9', x: 1, y: 6, length: 3, direction: 'RIGHT', color: '#eab308', type: 'van' },
    ],
    obstacles: [{ id: 'o1', x: 6, y: 0, width: 1, height: 1, type: 'barrier' }],
  },

  // 3. Hard Levels (16 - 25)
  {
    levelNumber: 16,
    difficulty: 'Hard',
    gridWidth: 7,
    gridHeight: 7,
    parMoves: 9,
    cars: [
      { id: 'c1', x: 1, y: 0, length: 2, direction: 'UP', color: '#3b82f6', type: 'sedan' },
      { id: 'c2', x: 2, y: 0, length: 3, direction: 'RIGHT', color: '#f43f5e', type: 'van' },
      { id: 'c3', x: 5, y: 1, length: 2, direction: 'DOWN', color: '#10b981', type: 'suv' },
      { id: 'c4', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#f59e0b', type: 'sedan' },
      { id: 'c5', x: 3, y: 2, length: 2, direction: 'DOWN', color: '#8b5cf6', type: 'sedan' },
      { id: 'c6', x: 4, y: 3, length: 2, direction: 'RIGHT', color: '#06b6d4', type: 'suv' },
      { id: 'c7', x: 1, y: 4, length: 3, direction: 'DOWN', color: '#6366f1', type: 'van' },
      { id: 'c8', x: 2, y: 4, length: 2, direction: 'RIGHT', color: '#ef4444', type: 'sedan' },
      { id: 'c9', x: 4, y: 5, length: 2, direction: 'DOWN', color: '#14b8a6', type: 'sedan' },
    ],
    obstacles: [
      { id: 'o1', x: 6, y: 2, width: 1, height: 1, type: 'cone' },
      { id: 'o2', x: 0, y: 6, width: 1, height: 1, type: 'hydrant' },
    ],
  },
  {
    levelNumber: 17,
    difficulty: 'Hard',
    gridWidth: 7,
    gridHeight: 7,
    parMoves: 10,
    cars: [
      { id: 'c1', x: 0, y: 1, length: 2, direction: 'RIGHT', color: '#ef4444', type: 'sedan' },
      { id: 'c2', x: 2, y: 0, length: 3, direction: 'DOWN', color: '#f97316', type: 'van' },
      { id: 'c3', x: 3, y: 0, length: 2, direction: 'RIGHT', color: '#3b82f6', type: 'suv' },
      { id: 'c4', x: 5, y: 1, length: 2, direction: 'DOWN', color: '#10b981', type: 'sedan' },
      { id: 'c5', x: 0, y: 3, length: 2, direction: 'LEFT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c6', x: 3, y: 2, length: 3, direction: 'DOWN', color: '#ec4899', type: 'van' },
      { id: 'c7', x: 4, y: 3, length: 2, direction: 'RIGHT', color: '#06b6d4', type: 'suv' },
      { id: 'c8', x: 1, y: 4, length: 2, direction: 'DOWN', color: '#eab308', type: 'sedan' },
      { id: 'c9', x: 3, y: 5, length: 3, direction: 'RIGHT', color: '#6366f1', type: 'van' },
      { id: 'c10', x: 0, y: 6, length: 2, direction: 'LEFT', color: '#14b8a6', type: 'sedan' },
    ],
    obstacles: [{ id: 'o1', x: 6, y: 4, width: 1, height: 1, type: 'barrier' }],
  },
  {
    levelNumber: 18,
    difficulty: 'Hard',
    gridWidth: 7,
    gridHeight: 7,
    parMoves: 10,
    cars: [
      { id: 'c1', x: 1, y: 0, length: 3, direction: 'RIGHT', color: '#3b82f6', type: 'van' },
      { id: 'c2', x: 4, y: 0, length: 2, direction: 'DOWN', color: '#ef4444', type: 'suv' },
      { id: 'c3', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#10b981', type: 'sedan' },
      { id: 'c4', x: 2, y: 1, length: 3, direction: 'DOWN', color: '#f59e0b', type: 'van' },
      { id: 'c5', x: 3, y: 2, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c6', x: 5, y: 2, length: 2, direction: 'DOWN', color: '#ec4899', type: 'suv' },
      { id: 'c7', x: 0, y: 4, length: 2, direction: 'RIGHT', color: '#06b6d4', type: 'sedan' },
      { id: 'c8', x: 3, y: 4, length: 2, direction: 'DOWN', color: '#14b8a6', type: 'sedan' },
      { id: 'c9', x: 4, y: 5, length: 2, direction: 'RIGHT', color: '#f43f5e', type: 'sedan' },
      { id: 'c10', x: 1, y: 6, length: 3, direction: 'RIGHT', color: '#6366f1', type: 'van' },
    ],
    obstacles: [
      { id: 'o1', x: 0, y: 0, width: 1, height: 1, type: 'planter' },
      { id: 'o2', x: 6, y: 0, width: 1, height: 1, type: 'cone' },
    ],
  },
  {
    levelNumber: 19,
    difficulty: 'Hard',
    gridWidth: 7,
    gridHeight: 7,
    parMoves: 10,
    cars: [
      { id: 'c1', x: 0, y: 0, length: 2, direction: 'RIGHT', color: '#10b981', type: 'sedan' },
      { id: 'c2', x: 2, y: 0, length: 2, direction: 'DOWN', color: '#3b82f6', type: 'suv' },
      { id: 'c3', x: 3, y: 0, length: 3, direction: 'RIGHT', color: '#f97316', type: 'van' },
      { id: 'c4', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#ef4444', type: 'sedan' },
      { id: 'c5', x: 4, y: 1, length: 3, direction: 'DOWN', color: '#6366f1', type: 'van' },
      { id: 'c6', x: 1, y: 3, length: 2, direction: 'DOWN', color: '#8b5cf6', type: 'sedan' },
      { id: 'c7', x: 2, y: 3, length: 2, direction: 'RIGHT', color: '#ec4899', type: 'suv' },
      { id: 'c8', x: 5, y: 3, length: 2, direction: 'DOWN', color: '#06b6d4', type: 'sedan' },
      { id: 'c9', x: 0, y: 5, length: 3, direction: 'RIGHT', color: '#14b8a6', type: 'van' },
      { id: 'c10', x: 3, y: 5, length: 2, direction: 'DOWN', color: '#eab308', type: 'sedan' },
    ],
    obstacles: [{ id: 'o1', x: 6, y: 6, width: 1, height: 1, type: 'hydrant' }],
  },
  {
    levelNumber: 20,
    difficulty: 'Hard',
    gridWidth: 8,
    gridHeight: 8,
    parMoves: 11,
    cars: [
      { id: 'c1', x: 1, y: 0, length: 2, direction: 'UP', color: '#3b82f6', type: 'sedan' },
      { id: 'c2', x: 2, y: 1, length: 3, direction: 'RIGHT', color: '#f43f5e', type: 'van' },
      { id: 'c3', x: 5, y: 0, length: 2, direction: 'DOWN', color: '#10b981', type: 'suv' },
      { id: 'c4', x: 6, y: 1, length: 2, direction: 'RIGHT', color: '#ef4444', type: 'sedan' },
      { id: 'c5', x: 0, y: 3, length: 2, direction: 'LEFT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c6', x: 3, y: 2, length: 3, direction: 'DOWN', color: '#6366f1', type: 'van' },
      { id: 'c7', x: 4, y: 3, length: 2, direction: 'RIGHT', color: '#06b6d4', type: 'suv' },
      { id: 'c8', x: 1, y: 4, length: 2, direction: 'DOWN', color: '#f59e0b', type: 'sedan' },
      { id: 'c9', x: 2, y: 5, length: 3, direction: 'RIGHT', color: '#14b8a6', type: 'van' },
      { id: 'c10', x: 6, y: 4, length: 2, direction: 'DOWN', color: '#ec4899', type: 'sedan' },
      { id: 'c11', x: 4, y: 6, length: 2, direction: 'DOWN', color: '#eab308', type: 'suv' },
    ],
    obstacles: [
      { id: 'o1', x: 0, y: 0, width: 1, height: 1, type: 'cone' },
      { id: 'o2', x: 7, y: 7, width: 1, height: 1, type: 'barrier' },
    ],
  },
  {
    levelNumber: 21,
    difficulty: 'Hard',
    gridWidth: 8,
    gridHeight: 8,
    parMoves: 11,
    cars: [
      { id: 'c1', x: 0, y: 1, length: 3, direction: 'RIGHT', color: '#f97316', type: 'van' },
      { id: 'c2', x: 3, y: 0, length: 2, direction: 'DOWN', color: '#3b82f6', type: 'sedan' },
      { id: 'c3', x: 5, y: 0, length: 2, direction: 'RIGHT', color: '#10b981', type: 'suv' },
      { id: 'c4', x: 0, y: 3, length: 2, direction: 'LEFT', color: '#ef4444', type: 'sedan' },
      { id: 'c5', x: 2, y: 2, length: 3, direction: 'DOWN', color: '#6366f1', type: 'van' },
      { id: 'c6', x: 4, y: 2, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c7', x: 6, y: 2, length: 2, direction: 'DOWN', color: '#ec4899', type: 'suv' },
      { id: 'c8', x: 1, y: 5, length: 2, direction: 'DOWN', color: '#06b6d4', type: 'sedan' },
      { id: 'c9', x: 3, y: 4, length: 3, direction: 'DOWN', color: '#14b8a6', type: 'van' },
      { id: 'c10', x: 4, y: 5, length: 2, direction: 'RIGHT', color: '#f59e0b', type: 'suv' },
      { id: 'c11', x: 2, y: 7, length: 3, direction: 'RIGHT', color: '#f43f5e', type: 'van' },
    ],
    obstacles: [{ id: 'o1', x: 7, y: 0, width: 1, height: 1, type: 'planter' }],
  },
  {
    levelNumber: 22,
    difficulty: 'Hard',
    gridWidth: 8,
    gridHeight: 8,
    parMoves: 12,
    cars: [
      { id: 'c1', x: 1, y: 0, length: 2, direction: 'UP', color: '#3b82f6', type: 'sedan' },
      { id: 'c2', x: 3, y: 0, length: 3, direction: 'RIGHT', color: '#6366f1', type: 'van' },
      { id: 'c3', x: 6, y: 1, length: 2, direction: 'DOWN', color: '#ef4444', type: 'suv' },
      { id: 'c4', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#10b981', type: 'sedan' },
      { id: 'c5', x: 2, y: 1, length: 3, direction: 'DOWN', color: '#f59e0b', type: 'van' },
      { id: 'c6', x: 3, y: 2, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c7', x: 5, y: 3, length: 2, direction: 'DOWN', color: '#06b6d4', type: 'suv' },
      { id: 'c8', x: 0, y: 4, length: 2, direction: 'RIGHT', color: '#ec4899', type: 'sedan' },
      { id: 'c9', x: 3, y: 4, length: 3, direction: 'DOWN', color: '#14b8a6', type: 'van' },
      { id: 'c10', x: 4, y: 5, length: 2, direction: 'RIGHT', color: '#eab308', type: 'suv' },
      { id: 'c11', x: 1, y: 6, length: 2, direction: 'DOWN', color: '#f43f5e', type: 'sedan' },
      { id: 'c12', x: 4, y: 7, length: 3, direction: 'RIGHT', color: '#f97316', type: 'van' },
    ],
    obstacles: [
      { id: 'o1', x: 7, y: 3, width: 1, height: 1, type: 'cone' },
      { id: 'o2', x: 0, y: 7, width: 1, height: 1, type: 'barrier' },
    ],
  },
  {
    levelNumber: 23,
    difficulty: 'Hard',
    gridWidth: 8,
    gridHeight: 8,
    parMoves: 12,
    cars: [
      { id: 'c1', x: 0, y: 0, length: 2, direction: 'RIGHT', color: '#10b981', type: 'sedan' },
      { id: 'c2', x: 2, y: 0, length: 2, direction: 'DOWN', color: '#3b82f6', type: 'suv' },
      { id: 'c3', x: 4, y: 0, length: 3, direction: 'RIGHT', color: '#f97316', type: 'van' },
      { id: 'c4', x: 7, y: 1, length: 2, direction: 'DOWN', color: '#ef4444', type: 'sedan' },
      { id: 'c5', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c6', x: 3, y: 1, length: 3, direction: 'DOWN', color: '#6366f1', type: 'van' },
      { id: 'c7', x: 5, y: 2, length: 2, direction: 'RIGHT', color: '#06b6d4', type: 'suv' },
      { id: 'c8', x: 1, y: 4, length: 2, direction: 'DOWN', color: '#ec4899', type: 'sedan' },
      { id: 'c9', x: 4, y: 3, length: 3, direction: 'DOWN', color: '#14b8a6', type: 'van' },
      { id: 'c10', x: 5, y: 4, length: 2, direction: 'RIGHT', color: '#f59e0b', type: 'suv' },
      { id: 'c11', x: 2, y: 6, length: 3, direction: 'RIGHT', color: '#f43f5e', type: 'van' },
      { id: 'c12', x: 6, y: 5, length: 2, direction: 'DOWN', color: '#eab308', type: 'sedan' },
    ],
    obstacles: [{ id: 'o1', x: 0, y: 6, width: 1, height: 1, type: 'hydrant' }],
  },
  {
    levelNumber: 24,
    difficulty: 'Hard',
    gridWidth: 8,
    gridHeight: 8,
    parMoves: 12,
    cars: [
      { id: 'c1', x: 1, y: 0, length: 3, direction: 'RIGHT', color: '#3b82f6', type: 'van' },
      { id: 'c2', x: 4, y: 0, length: 2, direction: 'DOWN', color: '#ef4444', type: 'suv' },
      { id: 'c3', x: 6, y: 0, length: 2, direction: 'RIGHT', color: '#10b981', type: 'sedan' },
      { id: 'c4', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#f59e0b', type: 'sedan' },
      { id: 'c5', x: 2, y: 1, length: 3, direction: 'DOWN', color: '#6366f1', type: 'van' },
      { id: 'c6', x: 5, y: 2, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c7', x: 7, y: 2, length: 2, direction: 'DOWN', color: '#06b6d4', type: 'suv' },
      { id: 'c8', x: 0, y: 4, length: 2, direction: 'RIGHT', color: '#ec4899', type: 'sedan' },
      { id: 'c9', x: 3, y: 3, length: 3, direction: 'DOWN', color: '#14b8a6', type: 'van' },
      { id: 'c10', x: 4, y: 4, length: 2, direction: 'RIGHT', color: '#f43f5e', type: 'suv' },
      { id: 'c11', x: 1, y: 6, length: 2, direction: 'DOWN', color: '#eab308', type: 'sedan' },
      { id: 'c12', x: 4, y: 6, length: 3, direction: 'RIGHT', color: '#f97316', type: 'van' },
    ],
    obstacles: [
      { id: 'o1', x: 7, y: 7, width: 1, height: 1, type: 'planter' },
      { id: 'o2', x: 0, y: 0, width: 1, height: 1, type: 'cone' },
    ],
  },
  {
    levelNumber: 25,
    difficulty: 'Hard',
    gridWidth: 8,
    gridHeight: 8,
    parMoves: 13,
    cars: [
      { id: 'c1', x: 0, y: 1, length: 2, direction: 'RIGHT', color: '#3b82f6', type: 'sedan' },
      { id: 'c2', x: 2, y: 0, length: 3, direction: 'DOWN', color: '#f97316', type: 'van' },
      { id: 'c3', x: 3, y: 0, length: 2, direction: 'RIGHT', color: '#10b981', type: 'suv' },
      { id: 'c4', x: 5, y: 0, length: 2, direction: 'DOWN', color: '#ef4444', type: 'sedan' },
      { id: 'c5', x: 0, y: 3, length: 2, direction: 'LEFT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c6', x: 3, y: 2, length: 3, direction: 'DOWN', color: '#6366f1', type: 'van' },
      { id: 'c7', x: 4, y: 2, length: 2, direction: 'RIGHT', color: '#06b6d4', type: 'suv' },
      { id: 'c8', x: 6, y: 2, length: 2, direction: 'DOWN', color: '#ec4899', type: 'sedan' },
      { id: 'c9', x: 1, y: 4, length: 2, direction: 'DOWN', color: '#f59e0b', type: 'sedan' },
      { id: 'c10', x: 4, y: 4, length: 3, direction: 'DOWN', color: '#14b8a6', type: 'van' },
      { id: 'c11', x: 5, y: 5, length: 2, direction: 'RIGHT', color: '#f43f5e', type: 'suv' },
      { id: 'c12', x: 2, y: 6, length: 2, direction: 'DOWN', color: '#eab308', type: 'sedan' },
      { id: 'c13', x: 4, y: 7, length: 3, direction: 'RIGHT', color: '#3b82f6', type: 'van' },
    ],
    obstacles: [{ id: 'o1', x: 7, y: 0, width: 1, height: 1, type: 'barrier' }],
  },

  // 4. Expert Levels (26 - 30)
  {
    levelNumber: 26,
    difficulty: 'Expert',
    gridWidth: 8,
    gridHeight: 8,
    parMoves: 13,
    cars: [
      { id: 'c1', x: 0, y: 0, length: 3, direction: 'RIGHT', color: '#f43f5e', type: 'van' },
      { id: 'c2', x: 3, y: 0, length: 2, direction: 'DOWN', color: '#3b82f6', type: 'sedan' },
      { id: 'c3', x: 4, y: 1, length: 3, direction: 'RIGHT', color: '#6366f1', type: 'van' },
      { id: 'c4', x: 7, y: 0, length: 2, direction: 'DOWN', color: '#ef4444', type: 'suv' },
      { id: 'c5', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#10b981', type: 'sedan' },
      { id: 'c6', x: 2, y: 2, length: 3, direction: 'DOWN', color: '#f59e0b', type: 'van' },
      { id: 'c7', x: 3, y: 3, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'sedan' },
      { id: 'c8', x: 5, y: 2, length: 3, direction: 'DOWN', color: '#14b8a6', type: 'van' },
      { id: 'c9', x: 6, y: 3, length: 2, direction: 'RIGHT', color: '#06b6d4', type: 'suv' },
      { id: 'c10', x: 0, y: 4, length: 2, direction: 'RIGHT', color: '#ec4899', type: 'sedan' },
      { id: 'c11', x: 3, y: 5, length: 2, direction: 'DOWN', color: '#eab308', type: 'suv' },
      { id: 'c12', x: 1, y: 6, length: 2, direction: 'DOWN', color: '#f97316', type: 'sedan' },
      { id: 'c13', x: 4, y: 6, length: 3, direction: 'RIGHT', color: '#3b82f6', type: 'van' },
    ],
    obstacles: [
      { id: 'o1', x: 7, y: 7, width: 1, height: 1, type: 'cone' },
      { id: 'o2', x: 0, y: 7, width: 1, height: 1, type: 'hydrant' },
    ],
  },
  {
    levelNumber: 27,
    difficulty: 'Expert',
    gridWidth: 8,
    gridHeight: 8,
    parMoves: 14,
    cars: [
      { id: 'c1', x: 1, y: 0, length: 2, direction: 'UP', color: '#3b82f6', type: 'sedan' },
      { id: 'c2', x: 2, y: 0, length: 3, direction: 'RIGHT', color: '#6366f1', type: 'van' },
      { id: 'c3', x: 5, y: 0, length: 2, direction: 'DOWN', color: '#ef4444', type: 'suv' },
      { id: 'c4', x: 6, y: 1, length: 2, direction: 'RIGHT', color: '#10b981', type: 'sedan' },
      { id: 'c5', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#f59e0b', type: 'sedan' },
      { id: 'c6', x: 3, y: 1, length: 3, direction: 'DOWN', color: '#f43f5e', type: 'van' },
      { id: 'c7', x: 4, y: 2, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'suv' },
      { id: 'c8', x: 1, y: 3, length: 3, direction: 'DOWN', color: '#14b8a6', type: 'van' },
      { id: 'c9', x: 6, y: 3, length: 2, direction: 'DOWN', color: '#06b6d4', type: 'sedan' },
      { id: 'c10', x: 2, y: 4, length: 2, direction: 'RIGHT', color: '#ec4899', type: 'sedan' },
      { id: 'c11', x: 4, y: 4, length: 3, direction: 'DOWN', color: '#f97316', type: 'van' },
      { id: 'c12', x: 5, y: 5, length: 2, direction: 'RIGHT', color: '#eab308', type: 'suv' },
      { id: 'c13', x: 0, y: 6, length: 3, direction: 'RIGHT', color: '#3b82f6', type: 'van' },
      { id: 'c14', x: 3, y: 7, length: 2, direction: 'DOWN', color: '#10b981', type: 'sedan' },
    ],
    obstacles: [
      { id: 'o1', x: 0, y: 0, width: 1, height: 1, type: 'barrier' },
      { id: 'o2', x: 7, y: 6, width: 1, height: 1, type: 'planter' },
    ],
  },
  {
    levelNumber: 28,
    difficulty: 'Expert',
    gridWidth: 8,
    gridHeight: 8,
    parMoves: 14,
    cars: [
      { id: 'c1', x: 0, y: 0, length: 2, direction: 'RIGHT', color: '#10b981', type: 'sedan' },
      { id: 'c2', x: 2, y: 0, length: 3, direction: 'DOWN', color: '#f97316', type: 'van' },
      { id: 'c3', x: 3, y: 0, length: 2, direction: 'RIGHT', color: '#3b82f6', type: 'suv' },
      { id: 'c4', x: 5, y: 0, length: 3, direction: 'RIGHT', color: '#6366f1', type: 'van' },
      { id: 'c5', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#ef4444', type: 'sedan' },
      { id: 'c6', x: 4, y: 1, length: 3, direction: 'DOWN', color: '#f43f5e', type: 'van' },
      { id: 'c7', x: 5, y: 2, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'suv' },
      { id: 'c8', x: 7, y: 2, length: 2, direction: 'DOWN', color: '#06b6d4', type: 'sedan' },
      { id: 'c9', x: 1, y: 3, length: 3, direction: 'DOWN', color: '#14b8a6', type: 'van' },
      { id: 'c10', x: 2, y: 4, length: 2, direction: 'RIGHT', color: '#ec4899', type: 'sedan' },
      { id: 'c11', x: 6, y: 4, length: 2, direction: 'DOWN', color: '#f59e0b', type: 'suv' },
      { id: 'c12', x: 3, y: 5, length: 3, direction: 'DOWN', color: '#3b82f6', type: 'van' },
      { id: 'c13', x: 4, y: 6, length: 2, direction: 'RIGHT', color: '#eab308', type: 'sedan' },
      { id: 'c14', x: 0, y: 7, length: 3, direction: 'RIGHT', color: '#f97316', type: 'van' },
    ],
    obstacles: [
      { id: 'o1', x: 7, y: 0, width: 1, height: 1, type: 'cone' },
      { id: 'o2', x: 7, y: 7, width: 1, height: 1, type: 'hydrant' },
    ],
  },
  {
    levelNumber: 29,
    difficulty: 'Expert',
    gridWidth: 8,
    gridHeight: 8,
    parMoves: 15,
    cars: [
      { id: 'c1', x: 0, y: 1, length: 3, direction: 'RIGHT', color: '#6366f1', type: 'van' },
      { id: 'c2', x: 3, y: 0, length: 2, direction: 'DOWN', color: '#3b82f6', type: 'sedan' },
      { id: 'c3', x: 4, y: 0, length: 2, direction: 'RIGHT', color: '#10b981', type: 'suv' },
      { id: 'c4', x: 6, y: 0, length: 2, direction: 'DOWN', color: '#ef4444', type: 'sedan' },
      { id: 'c5', x: 0, y: 3, length: 2, direction: 'LEFT', color: '#f59e0b', type: 'sedan' },
      { id: 'c6', x: 2, y: 2, length: 3, direction: 'DOWN', color: '#f43f5e', type: 'van' },
      { id: 'c7', x: 4, y: 2, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'suv' },
      { id: 'c8', x: 7, y: 1, length: 3, direction: 'DOWN', color: '#14b8a6', type: 'van' },
      { id: 'c9', x: 3, y: 3, length: 3, direction: 'DOWN', color: '#f97316', type: 'van' },
      { id: 'c10', x: 5, y: 4, length: 2, direction: 'DOWN', color: '#06b6d4', type: 'sedan' },
      { id: 'c11', x: 0, y: 5, length: 2, direction: 'RIGHT', color: '#ec4899', type: 'suv' },
      { id: 'c12', x: 2, y: 6, length: 2, direction: 'DOWN', color: '#eab308', type: 'sedan' },
      { id: 'c13', x: 4, y: 6, length: 3, direction: 'RIGHT', color: '#3b82f6', type: 'van' },
      { id: 'c14', x: 0, y: 7, length: 2, direction: 'LEFT', color: '#10b981', type: 'sedan' },
    ],
    obstacles: [
      { id: 'o1', x: 0, y: 0, width: 1, height: 1, type: 'barrier' },
      { id: 'o2', x: 7, y: 7, width: 1, height: 1, type: 'planter' },
    ],
  },
  {
    levelNumber: 30,
    difficulty: 'Expert',
    gridWidth: 8,
    gridHeight: 8,
    parMoves: 16,
    cars: [
      { id: 'c1', x: 0, y: 0, length: 2, direction: 'RIGHT', color: '#f43f5e', type: 'sedan' },
      { id: 'c2', x: 2, y: 0, length: 3, direction: 'DOWN', color: '#3b82f6', type: 'van' },
      { id: 'c3', x: 3, y: 0, length: 3, direction: 'RIGHT', color: '#6366f1', type: 'van' },
      { id: 'c4', x: 6, y: 0, length: 2, direction: 'DOWN', color: '#ef4444', type: 'suv' },
      { id: 'c5', x: 0, y: 2, length: 2, direction: 'LEFT', color: '#10b981', type: 'sedan' },
      { id: 'c6', x: 4, y: 1, length: 3, direction: 'DOWN', color: '#f97316', type: 'van' },
      { id: 'c7', x: 5, y: 2, length: 2, direction: 'RIGHT', color: '#8b5cf6', type: 'suv' },
      { id: 'c8', x: 7, y: 1, length: 3, direction: 'DOWN', color: '#14b8a6', type: 'van' },
      { id: 'c9', x: 1, y: 3, length: 3, direction: 'DOWN', color: '#f59e0b', type: 'van' },
      { id: 'c10', x: 2, y: 4, length: 2, direction: 'RIGHT', color: '#06b6d4', type: 'sedan' },
      { id: 'c11', x: 5, y: 4, length: 2, direction: 'DOWN', color: '#ec4899', type: 'suv' },
      { id: 'c12', x: 0, y: 6, length: 2, direction: 'RIGHT', color: '#eab308', type: 'sedan' },
      { id: 'c13', x: 3, y: 5, length: 3, direction: 'DOWN', color: '#3b82f6', type: 'van' },
      { id: 'c14', x: 4, y: 6, length: 2, direction: 'RIGHT', color: '#10b981', type: 'suv' },
      { id: 'c15', x: 0, y: 7, length: 3, direction: 'RIGHT', color: '#f43f5e', type: 'van' },
    ],
    obstacles: [
      { id: 'o1', x: 7, y: 0, width: 1, height: 1, type: 'hydrant' },
      { id: 'o2', x: 0, y: 7, width: 1, height: 1, type: 'barrier' },
      { id: 'o3', x: 7, y: 7, width: 1, height: 1, type: 'cone' },
    ],
  },
];
