export const LEVELS = [
  {
    id: 1,
    name: 'Training Dock',
    parMoves: 14,
    decorations: [
      { type: 'barrel', x: 1, y: 3 },
      { type: 'pallet', x: 4, y: 3 },
    ],
    grid: [
      '######',
      '#@ $.#',
      '# $ .#',
      '#    #',
      '######',
    ],
  },
  {
    id: 2,
    name: 'Crossroads Bay',
    parMoves: 22,
    decorations: [
      { type: 'barrel', x: 1, y: 3 },
      { type: 'pallet', x: 5, y: 4 },
    ],
    grid: [
      '#######',
      '#  .  #',
      '# $#$ #',
      '#  @  #',
      '#  .  #',
      '#######',
    ],
  },
  {
    id: 3,
    name: 'Warehouse Bay 3',
    parMoves: 38,
    decorations: [
      { type: 'barrel', x: 1, y: 5 },
      { type: 'pallet', x: 6, y: 1 },
    ],
    grid: [
      '########',
      '#  .   #',
      '#  $   #',
      '# @$ . #',
      '#  $   #',
      '#   .  #',
      '########',
    ],
  },
  {
    id: 4,
    name: 'Corner Caution',
    parMoves: 28,
    decorations: [
      { type: 'barrel', x: 6, y: 1 },
      { type: 'pallet', x: 1, y: 4 },
    ],
    grid: [
      '########',
      '#@     #',
      '# $$ #.#',
      '# #  #.#',
      '#    #.#',
      '# $    #',
      '########',
    ],
  },
  {
    id: 5,
    name: 'Cargo Siding',
    parMoves: 34,
    decorations: [
      { type: 'barrel', x: 1, y: 1 },
      { type: 'pallet', x: 6, y: 5 },
    ],
    grid: [
      '########',
      '#   .  #',
      '#  $#$ #',
      '# . @ .#',
      '#  $#$ #',
      '#   .  #',
      '########',
    ],
  },
  {
    id: 6,
    name: 'Pallet Alley',
    parMoves: 45,
    decorations: [
      { type: 'barrel', x: 7, y: 1 },
      { type: 'pallet', x: 1, y: 6 },
    ],
    grid: [
      '#########',
      '# . #   #',
      '# $   $ #',
      '# @ # # #',
      '# $   $ #',
      '# . # . #',
      '#       #',
      '#########',
    ],
  },
  {
    id: 7,
    name: 'Loading Dock Beta',
    parMoves: 32,
    decorations: [
      { type: 'pallet', x: 6, y: 1 },
      { type: 'barrel', x: 1, y: 5 },
    ],
    grid: [
      '########',
      '#   #  #',
      '# $ .  #',
      '# @$#  #',
      '#  . $ #',
      '#    . #',
      '########',
    ],
  },
  {
    id: 8,
    name: 'Forklift Turn',
    parMoves: 50,
    decorations: [
      { type: 'barrel', x: 1, y: 1 },
      { type: 'pallet', x: 7, y: 5 },
    ],
    grid: [
      '#########',
      '#   .   #',
      '#  $#$  #',
      '# . $ . #',
      '#  $@$  #',
      '#   .   #',
      '#########',
    ],
  },
  {
    id: 9,
    name: 'Heavy Freight',
    parMoves: 46,
    decorations: [
      { type: 'pallet', x: 1, y: 1 },
      { type: 'barrel', x: 7, y: 5 },
    ],
    grid: [
      '#########',
      '# .   . #',
      '#  $$$  #',
      '#  #@#  #',
      '#  $$$  #',
      '# .   . #',
      '#########',
    ],
  },
  {
    id: 10,
    name: 'Central Depot',
    parMoves: 55,
    decorations: [
      { type: 'barrel', x: 8, y: 1 },
      { type: 'pallet', x: 1, y: 4 },
    ],
    grid: [
      '##########',
      '# .  #   #',
      '# # $  $ #',
      '#  @##   #',
      '# $  $ . #',
      '# .  # . #',
      '##########',
    ],
  },
  {
    id: 11,
    name: 'Logistics Vault',
    parMoves: 60,
    decorations: [
      { type: 'pallet', x: 1, y: 1 },
      { type: 'barrel', x: 8, y: 5 },
    ],
    grid: [
      '##########',
      '#   ..   #',
      '#  $$$$  #',
      '#  #  #  #',
      '#   @    #',
      '#   ..   #',
      '##########',
    ],
  },
  {
    id: 12,
    name: 'Grand Warehouse',
    parMoves: 72,
    decorations: [
      { type: 'pallet', x: 1, y: 1 },
      { type: 'barrel', x: 9, y: 5 },
    ],
    grid: [
      '###########',
      '#   ...   #',
      '#  $ # $  #',
      '# $  @  $ #',
      '#  $ # $  #',
      '#   ...   #',
      '###########',
    ],
  },
];
